### PR TITLE
listen to scroll direction

### PR DESCRIPTION
**Pull request by mipreamble**

### CODE REVIEW

**Comment by vinaysshenoy** [comment]
@mipreamble We can add this, but should we? mugen's responsibility is only to enable infinite scroll, nothing else.

**Comment by mipreamble** [comment]
@vinaysshenoy Lets add this as an add on.
We are already using ScrollListener. This can automatically detect scroll up and down.

This can be optional. My implementation was forced. Can be removed.
```java
baseAttacher.setOnScrollStateListner(new Mugen.ScrollStateListener() {
         void  scrollStateChanged(int direction){

         }
}
```

**Comment by vinaysshenoy** [comment]
Cool. In what cases will providing this be useful?

**Comment by mipreamble** [comment]
@vinaysshenoy We need lot of other details for this to be useful.

This will specifically be useful if you want hide actionbar / hide floating action bar depending on the scrolling direction.

However, we would need to track the speed of scroll and various other details for that. 
It will be a nice thing to have.

Closing this for now. Will come back with more details later.

**Pull request closed without merging**
